import { createAction, props } from '@ngrx/store';
export const loadUsers = createAction('[Users] Load Users');
export const loadUsersSuccess = createAction('[Users] Load Users Success', props<{ users: any[] }>() );
export const loadUsersFailure = createAction('[Users] Load Users Failure', props<{ error: string }>() );
export const addUser = createAction('[Users] Add User', props<{ user: any }>() );
export const addUserSuccess = createAction('[Users] Add User Success', props<{ user: any }>() );
export const addUserFailure = createAction('[Users] Add User Failure', props<{ error: string }>() );
export const updateUser = createAction('[Users] Update User', props<{ user: any }>() );
export const updateUserSuccess = createAction('[Users] Update User Success', props<{ user: any }>() );
export const updateUserFailure = createAction('[Users] Update User Failure', props<{ error: string }>() );
export const deleteUser = createAction('[Users] Delete User', props<{ id: number }>() );
export const deleteUserSuccess = createAction('[Users] Delete User Success', props<{ id: number }>() );
export const deleteUserFailure = createAction('[Users] Delete User Failure', props<{ error: string }>() );
